# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaRowSums <- function(x) {
    .Call(`_HierMultinom_armaRowSums`, x)
}

eigenMatMult <- function(A, B) {
    .Call(`_HierMultinom_eigenMatMult`, A, B)
}

